USE       DATABASE DAS;
USE       SCHEMA DAS_HEALTHCARE_CLAIMS_RAW_DB;
USE ROLE  DAS_DLK_DAS_HEALTHCARE_CLAIMS_DO_GRP;
USE       WAREHOUSE DAS_SFK_XS_WH;


/* Build a table of the highest-ranked description for every CUI.
MRCONSO contains all names/synonyms for each concept; MRRANK_OHIO supplies the ranking.
We select the "best" (rank-1) string per CUI to ensure consistent naming later. */
CREATE    OR REPLACE TABLE TEMP_MRCONSO_CUI_DESCRIPTIONS_WEIGHTED AS
WITH      MR_RANKINGS AS (
          SELECT    M.CUI,
                    M.STR AS NAME,
                    M.CODE,
                    M.AUI,
                    M.SAB,
                    M.TTY,
                    R.RANK,
                    ROW_NUMBER() OVER (
                    PARTITION BY M.CUI, M.SAB
                    ORDER BY  R.RANK DESC
                    ) AS RN
          FROM      MRCONSO M
          JOIN      MRRANK_OHIO R ON M.SAB = R.SAB
          AND       M.TTY = R.TTY
          AND       M.LAT = 'ENG'
          )
SELECT    *
FROM      MR_RANKINGS
WHERE     RN = 1;

/*This ranking table is for MRREL SAB */
CREATE OR REPLACE TABLE TEMP_MRREL_SAB_RANK AS
SELECT 'RXNORM' AS SAB, 916 AS SAB_WEIGHT UNION ALL
SELECT 'MTH' , 915  UNION ALL
SELECT 'MTHCMSFRF', 914 UNION ALL
SELECT 'MSH', 892 UNION ALL
SELECT 'SNOMEDCT_US', 885 UNION ALL
SELECT 'SNOMEDCT_VET', 873 UNION ALL
SELECT 'HPO', 869 UNION ALL
SELECT 'NCBI', 866 UNION ALL
SELECT 'MTHSPL', 865 UNION ALL
SELECT 'ATC', 862 UNION ALL
SELECT 'VANDF', 860 UNION ALL
SELECT 'USP', 857 UNION ALL
SELECT 'USPMG', 855 UNION ALL
SELECT 'MMX', 853 UNION ALL
SELECT 'DRUGBANK', 849 UNION ALL
SELECT 'CPM', 843 UNION ALL
SELECT 'NEU', 842 UNION ALL
SELECT 'FMA', 840 UNION ALL
SELECT 'UWDA', 837 UNION ALL
SELECT 'UMD', 835 UNION ALL
SELECT 'GS', 831 UNION ALL
SELECT 'MMSL', 830 UNION ALL
SELECT 'NDDF', 814 UNION ALL
SELECT 'MED-RT', 808 UNION ALL
SELECT 'SPN', 805 UNION ALL
SELECT 'MDR', 804 UNION ALL
SELECT 'CPT', 792 UNION ALL
SELECT 'HCPT', 785 UNION ALL
SELECT 'HCPCS', 784 UNION ALL
SELECT 'CDT', 783 UNION ALL
SELECT 'MVX', 782 UNION ALL
SELECT 'CVX', 781 UNION ALL
SELECT 'HCDT', 778 UNION ALL
SELECT 'ICD10AE', 775 UNION ALL
SELECT 'ICD10', 774 UNION ALL
SELECT 'ICD10AMAE', 769 UNION ALL
SELECT 'ICD10AM', 768 UNION ALL
SELECT 'OMIM', 763 UNION ALL
SELECT 'MEDCIN', 754 UNION ALL
SELECT 'HGNC', 750 UNION ALL
SELECT 'ICNP', 743 UNION ALL
SELECT 'PNDS', 742 UNION ALL
SELECT 'NCI', 739 UNION ALL
SELECT 'PDQ', 727 UNION ALL
SELECT 'CHV', 723 UNION ALL
SELECT 'MEDLINEPLUS', 722 UNION ALL
SELECT 'MTHICPC2EAE', 721 UNION ALL
SELECT 'ICPC2EENG', 720 UNION ALL
SELECT 'MTHICPC2ICD10AE', 719 UNION ALL
SELECT 'SOP', 718 UNION ALL
SELECT 'ICF', 717 UNION ALL
SELECT 'ICF-CY', 713 UNION ALL
SELECT 'ICPC2ICD10ENG', 709 UNION ALL
SELECT 'ICPC', 708 UNION ALL
SELECT 'ICPC2P', 696 UNION ALL
SELECT 'AOT', 692 UNION ALL
SELECT 'GO', 690 UNION ALL
SELECT 'LNC', 668 UNION ALL
SELECT 'ICD10CM', 652 UNION ALL
SELECT 'ICD9CM', 651 UNION ALL
SELECT 'CCSR_ICD10PCS', 648 UNION ALL
SELECT 'CCSR_ICD10CM', 647 UNION ALL
SELECT 'CCS', 643 UNION ALL
SELECT 'ICD10PCS', 635 UNION ALL
SELECT 'ORPHANET', 619 UNION ALL
SELECT 'NUCCHCPT', 617 UNION ALL
SELECT 'HL7V3.0', 616 UNION ALL
SELECT 'CDCREC', 615 UNION ALL
SELECT 'HL7V2.5', 612 UNION ALL
SELECT 'CCC', 601 UNION ALL
SELECT 'NIC', 599 UNION ALL
SELECT 'NANDA-I', 597 UNION ALL
SELECT 'OMS', 593 UNION ALL
SELECT 'NOC', 584 UNION ALL
SELECT 'ALT', 577 UNION ALL
SELECT 'MTHICD9', 569 UNION ALL
SELECT 'PSY', 566 UNION ALL
SELECT 'LCH_NW', 559 UNION ALL
SELECT 'LCH', 558 UNION ALL
SELECT 'WHO', 547 UNION ALL
SELECT 'SNMI', 544 UNION ALL
SELECT 'SNM', 536 UNION ALL
SELECT 'RCD', 531 UNION ALL
SELECT 'RCDSA', 526 UNION ALL
SELECT 'RCDSY', 525 UNION ALL
SELECT 'RCDAE', 524 UNION ALL
SELECT 'CSP', 514 UNION ALL
SELECT 'DSM-5', 429 UNION ALL
SELECT 'DXP', 427 UNION ALL
SELECT 'RAM', 424 UNION ALL
SELECT 'ULT', 422 UNION ALL
SELECT 'BI', 421 UNION ALL
SELECT 'PCDS', 417 UNION ALL
SELECT 'MTHMST', 411 UNION ALL
SELECT 'DDB', 409 UNION ALL
SELECT 'CST', 407 UNION ALL
SELECT 'COSTAR', 406 UNION ALL
SELECT 'CCPSS', 402 UNION ALL
SELECT 'AOD', 398 UNION ALL
SELECT 'QMR', 388 UNION ALL
SELECT 'JABL', 387 UNION ALL
SELECT 'AIR', 383 UNION ALL
SELECT 'PPAC', 379 UNION ALL
SELECT 'MCM', 374 UNION ALL
SELECT 'SCTSPA', 372 UNION ALL
SELECT 'MSHPOR', 353 UNION ALL
SELECT 'MSHSPA', 350 UNION ALL
SELECT 'MSHCZE', 347 UNION ALL
SELECT 'MSHDUT', 341 UNION ALL
SELECT 'MSHSWE', 340 UNION ALL
SELECT 'MSHNOR', 337 UNION ALL
SELECT 'MSHGER', 336 UNION ALL
SELECT 'MSHFIN', 330 UNION ALL
SELECT 'MSHLAV', 329 UNION ALL
SELECT 'MSHSCR', 328 UNION ALL
SELECT 'MSHFRE', 327 UNION ALL
SELECT 'MSHITA', 320 UNION ALL
SELECT 'MSHJPN', 317 UNION ALL
SELECT 'MSHPOL', 316 UNION ALL
SELECT 'MSHRUS', 315 UNION ALL
SELECT 'KCD5', 313 UNION ALL
SELECT 'TKMT', 312 UNION ALL
SELECT 'MDRSPA', 307 UNION ALL
SELECT 'MDRDUT', 299 UNION ALL
SELECT 'MDRFRE', 291 UNION ALL
SELECT 'MDRGER', 283 UNION ALL
SELECT 'MDRITA', 275 UNION ALL
SELECT 'MDRISL', 274 UNION ALL
SELECT 'MDRJPN', 259 UNION ALL
SELECT 'MDRHRV', 242 UNION ALL
SELECT 'MDRLIT', 241 UNION ALL
SELECT 'MDRCZE', 240 UNION ALL
SELECT 'MDREST', 239 UNION ALL
SELECT 'MDRKOR', 238 UNION ALL
SELECT 'MDRHUN', 237 UNION ALL
SELECT 'MDRBPO', 236 UNION ALL
SELECT 'MDRPOR', 235 UNION ALL
SELECT 'MDRLAV', 234 UNION ALL
SELECT 'MDRSWE', 233 UNION ALL
SELECT 'MDRARA', 232 UNION ALL
SELECT 'MDRFIN', 231 UNION ALL
SELECT 'MDRGRE', 230 UNION ALL
SELECT 'MDRRUS', 229 UNION ALL
SELECT 'MDRPOL', 228 UNION ALL
SELECT 'WHOFRE', 120 UNION ALL
SELECT 'WHOGER', 119 UNION ALL
SELECT 'WHOPOR', 118 UNION ALL
SELECT 'WHOSPA', 117 UNION ALL
SELECT 'LNC-DE-DE', 116 UNION ALL
SELECT 'LNC-EL-GR', 112 UNION ALL
SELECT 'LNC-ES-AR', 110 UNION ALL
SELECT 'LNC-ES-MX', 106 UNION ALL
SELECT 'LNC-ES-ES', 102 UNION ALL
SELECT 'LNC-ET-EE', 100 UNION ALL
SELECT 'LNC-FR-BE', 98 UNION ALL
SELECT 'LNC-FR-CA', 96 UNION ALL
SELECT 'LNC-FR-FR', 94 UNION ALL
SELECT 'LNC-IT-IT', 90 UNION ALL
SELECT 'LNC-KO-KR', 88 UNION ALL
SELECT 'LNC-PL-PL', 86 UNION ALL
SELECT 'LNC-NL-NL', 84 UNION ALL
SELECT 'LNC-PT-BR', 80 UNION ALL
SELECT 'LNC-RU-RU', 76 UNION ALL
SELECT 'LNC-TR-TR', 74 UNION ALL
SELECT 'LNC-UK-UA', 72 UNION ALL
SELECT 'LNC-ZH-CN', 65 UNION ALL
SELECT 'LNC-DE-AT', 63 UNION ALL
SELECT 'MEDLINEPLUS_SPA', 60 UNION ALL
SELECT 'CPTSP', 46 UNION ALL
SELECT 'DMDUMD', 45 UNION ALL
SELECT 'DMDICD10', 42 UNION ALL
SELECT 'ICPCBAQ', 40 UNION ALL
SELECT 'ICPCDAN', 39 UNION ALL
SELECT 'ICPC2EDUT', 38 UNION ALL
SELECT 'ICD10DUT', 37 UNION ALL
SELECT 'ICPC2ICD10DUT', 35 UNION ALL
SELECT 'ICPCDUT', 34 UNION ALL
SELECT 'ICPCFIN', 33 UNION ALL
SELECT 'ICPCFRE', 32 UNION ALL
SELECT 'ICPCGER', 31 UNION ALL
SELECT 'ICPCHEB', 30 UNION ALL
SELECT 'ICPCHUN', 29 UNION ALL
SELECT 'ICPCITA', 28 UNION ALL
SELECT 'ICPCNOR', 27 UNION ALL
SELECT 'ICPCPOR', 26 UNION ALL
SELECT 'ICPCSPA', 25 UNION ALL
SELECT 'ICPCSWE', 24 UNION ALL
SELECT 'MTHMSTFRE', 10 UNION ALL
SELECT 'MTHMSTITA', 9 UNION ALL
SELECT 'SRC', 8;


/* Extract all NDC-CUI mappings from MRSAT.
- ATN='NDC' returns the NDC attribute values.
- SUPPRESS='N' filters out deprecated entries.
- Normalizes NDC by removing hyphens and requiring 11 digits. */
CREATE    OR REPLACE TABLE TEMP_MRSAT_NDC_LOOKUP AS
SELECT    DISTINCT CUI,
          REPLACE(ATV, '-', '') AS NDC
FROM      MRSAT
WHERE     ATN = 'NDC'
AND       LENGTH(REPLACE(ATV, '-', '')) = 11;


/* Determine the most representative CUI for each NDC based on MRRANK_OHIO.
Step 1: Rank all CUIs linked to an NDC using RxNorm ranking logic.
Step 2: Select the highest ranked CUI for each NDC.
Step 3: Attach the best-ranked description (from TEMP_MRCONSO_CUI_DESCRIPTIONS_WEIGHTED). */
CREATE    OR REPLACE TABLE TEMP_NDC_CUI_DESCRIPTION_BEST AS
WITH      NDC_CUI_RANKED AS (
          SELECT    N.NDC,
                    N.CUI,
                    R.RANK AS MRRANK_OHIO_SCORE,
                    ROW_NUMBER() OVER (
                    PARTITION BY N.NDC
                    ORDER BY  R.RANK DESC
                    ) AS RN
          FROM      TEMP_MRSAT_NDC_LOOKUP N
          JOIN      MRCONSO M ON N.CUI = M.CUI
          JOIN      MRRANK_OHIO R ON M.SAB = R.SAB
          AND       M.TTY = R.TTY
          ),
          BEST_CUI AS (
          SELECT    NDC,
                    CUI
          FROM      NDC_CUI_RANKED
          WHERE     RN = 1
          )
SELECT    B.NDC,
          B.CUI,
          D.NAME,
          D.CODE,
          D.AUI,
          D.SAB,
          D.TTY
FROM      BEST_CUI B
JOIN      TEMP_MRCONSO_CUI_DESCRIPTIONS_WEIGHTED D ON B.CUI = D.CUI;
