SELECT    REL.CUI2,
          W.NAME,
          REL.REL,
          REL.RELA,
          REL.CUI1,
          W2.NAME,
          W.SAB,
          W2.SAB,
          W2.TTY
FROM      MRREL REL
JOIN      TEMP_MRCONSO_CUI_DESCRIPTIONS_WEIGHTED W ON W.CUI = REL.CUI2
JOIN      TEMP_MRCONSO_CUI_DESCRIPTIONS_WEIGHTED W2 ON W2.CUI = REL.CUI1
WHERE     REL.CUI2 = 'C3885068'
AND       REL.RELA IS NOT NULL
ORDER BY  REL.RELA;