CREATE OR REPLACE TABLE MRDEF (
    CUI	VARCHAR(8) ,
    AUI	VARCHAR(9) ,
    ATUI VARCHAR(11) ,
    SATUI VARCHAR(50),
    SAB	VARCHAR(40) ,
    DEF	VARCHAR(16777216) ,
    SUPPRESS VARCHAR(1) ,
    CVF	VARCHAR 
);

CREATE OR REPLACE TABLE MRSTY (
    CUI	VARCHAR(8) ,
    TUI	VARCHAR(4) ,
    STN	VARCHAR(100) ,
    STY	VARCHAR(50) ,
    ATUI VARCHAR(11) ,
    CVF	VARCHAR 
);

CREATE OR REPLACE TABLE MRDOC (
    DOCKEY	VARCHAR(50) ,
    VALUE	VARCHAR(200),
    TYPE	VARCHAR(50) ,
    EXPL	VARCHAR(16777216) 
);

CREATE OR REPLACE TABLE MRRANK (
    MRRANK_RANK	INTEGER , 
    SAB	VARCHAR(40) ,
    TTY	VARCHAR(40) ,
    SUPPRESS	VARCHAR(1) 
);
CREATE OR REPLACE TABLE MRHIER (
    CUI	VARCHAR(8) ,
    AUI	VARCHAR(9) ,
    CXN	INTEGER , 
    PAUI VARCHAR(10),
    SAB	VARCHAR(40) ,
    RELA VARCHAR(100),
    PTR	VARCHAR(16777216), 
    HCD	VARCHAR(100),
    CVF	VARCHAR
);

CREATE OR REPLACE TABLE MRSAB (
    VCUI VARCHAR(8),
    RCUI VARCHAR(8),
    VSAB VARCHAR(40) ,
    RSAB VARCHAR(40) ,
    SON	VARCHAR(16777216) , -- TEXT equivalent
    SF	VARCHAR(40) ,
    SVER VARCHAR(40),
    VSTART VARCHAR(8),
    VEND VARCHAR(8),
    IMETA VARCHAR(10) ,
    RMETA VARCHAR(10),
    SLC	VARCHAR(16777216), -- TEXT equivalent
    SCC	VARCHAR(16777216), -- TEXT equivalent
    SRL	INTEGER , -- int unsigned replaced with INTEGER
    TFR	INTEGER, -- int unsigned replaced with INTEGER
    CFR	INTEGER, -- int unsigned replaced with INTEGER
    CXTY VARCHAR(50),
    TTYL VARCHAR(400),
    ATNL VARCHAR(16777216), -- TEXT equivalent
    LAT	VARCHAR(3),
    CENC VARCHAR(40) ,
    CURVER VARCHAR(1) ,
    SABIN VARCHAR(1) ,
    SSN	VARCHAR(16777216) , -- TEXT equivalent
    SCIT VARCHAR(16777216)  -- TEXT equivalent
);



COPY INTO MRDEF
FROM @IOP_10005270.HEALTHCARE.UMLS_STAGE/MRDEF.RRF
FILE_FORMAT = (FORMAT_NAME='IOP_10005270.HEALTHCARE.UMLS_RRF_FORMAT');


COPY INTO MRDOC
FROM @IOP_10005270.HEALTHCARE.UMLS_STAGE/MRDOC.RRF
FILE_FORMAT = (FORMAT_NAME='IOP_10005270.HEALTHCARE.UMLS_RRF_FORMAT');


COPY INTO MRHIER
FROM @IOP_10005270.HEALTHCARE.UMLS_STAGE/MRHIER.RRF
FILE_FORMAT = (FORMAT_NAME='IOP_10005270.HEALTHCARE.UMLS_RRF_FORMAT');


COPY INTO MRRANK
FROM @IOP_10005270.HEALTHCARE.UMLS_STAGE/MRRANK.RRF
FILE_FORMAT = (FORMAT_NAME='IOP_10005270.HEALTHCARE.UMLS_RRF_FORMAT');


COPY INTO MRSAB
FROM @IOP_10005270.HEALTHCARE.UMLS_STAGE/MRSAB.RRF
FILE_FORMAT = (FORMAT_NAME='IOP_10005270.HEALTHCARE.UMLS_RRF_FORMAT');


COPY INTO MRSTY
FROM @IOP_10005270.HEALTHCARE.UMLS_STAGE/MRSTY.RRF
FILE_FORMAT = (FORMAT_NAME='IOP_10005270.HEALTHCARE.UMLS_RRF_FORMAT');