snow sql -q "PUT 'file:///Users/aaron.white/UMLS/RXNORM/RXNCUI.RRF' @IOP_10005270.HEALTHCARE.UMLS_STAGE AUTO_COMPRESS=TRUE;"
snow sql -q "PUT 'file:///Users/aaron.white/UMLS/RXNORM/RXNDOC.RRF' @IOP_10005270.HEALTHCARE.UMLS_STAGE AUTO_COMPRESS=TRUE;"
snow sql -q "PUT 'file:///Users/aaron.white/UMLS/RXNORM/RXNSAB.RRF' @IOP_10005270.HEALTHCARE.UMLS_STAGE AUTO_COMPRESS=TRUE;"
snow sql -q "PUT 'file:///Users/aaron.white/UMLS/RXNORM/RXNCONSO.RRF' @IOP_10005270.HEALTHCARE.UMLS_STAGE AUTO_COMPRESS=TRUE;"
snow sql -q "PUT 'file:///Users/aaron.white/UMLS/RXNORM/RXNSTY.RRF' @IOP_10005270.HEALTHCARE.UMLS_STAGE AUTO_COMPRESS=TRUE;"
snow sql -q "PUT 'file:///Users/aaron.white/UMLS/RXNORM/RNXREL.RRF' @IOP_10005270.HEALTHCARE.UMLS_STAGE AUTO_COMPRESS=TRUE;"
snow sql -q "PUT 'file:///Users/aaron.white/UMLS/RXNORM/RXNSAT.RRF' @IOP_10005270.HEALTHCARE.UMLS_STAGE AUTO_COMPRESS=TRUE;"
snow sql -q "PUT 'file:///Users/aaron.white/UMLS/RXNORM/RXNCUICHANGES.RRF' @IOP_10005270.HEALTHCARE.UMLS_STAGE AUTO_COMPRESS=TRUE;"


