snow sql -q "PUT 'file:///Users/aaron.white/UMLS/RXNORM/RXNCUI_20251207.RRF' @DAS.DAS_HEALTHCARE_CLAIMS_RAW_DB.DAS_HEALTHCARE_CLAIMS_RAW_DB_INTERNAL_STAGE AUTO_COMPRESS=TRUE;"
snow sql -q "PUT 'file:///Users/aaron.white/UMLS/RXNORM/RXNDOC_20251207.RRF' @DAS.DAS_HEALTHCARE_CLAIMS_RAW_DB.DAS_HEALTHCARE_CLAIMS_RAW_DB_INTERNAL_STAGE AUTO_COMPRESS=TRUE;"
snow sql -q "PUT 'file:///Users/aaron.white/UMLS/RXNORM/RXNSAB_20251207.RRF' @DAS.DAS_HEALTHCARE_CLAIMS_RAW_DB.DAS_HEALTHCARE_CLAIMS_RAW_DB_INTERNAL_STAGE AUTO_COMPRESS=TRUE;"
snow sql -q "PUT 'file:///Users/aaron.white/UMLS/RXNORM/RXNCONSO_20251207.RRF' @DAS.DAS_HEALTHCARE_CLAIMS_RAW_DB.DAS_HEALTHCARE_CLAIMS_RAW_DB_INTERNAL_STAGE AUTO_COMPRESS=TRUE;"
snow sql -q "PUT 'file:///Users/aaron.white/UMLS/RXNORM/RXNSTY_20251207.RRF' @DAS.DAS_HEALTHCARE_CLAIMS_RAW_DB.DAS_HEALTHCARE_CLAIMS_RAW_DB_INTERNAL_STAGE AUTO_COMPRESS=TRUE;"
snow sql -q "PUT 'file:///Users/aaron.white/UMLS/RXNORM/RXNREL_20251207.RRF' @DAS.DAS_HEALTHCARE_CLAIMS_RAW_DB.DAS_HEALTHCARE_CLAIMS_RAW_DB_INTERNAL_STAGE AUTO_COMPRESS=TRUE;"
snow sql -q "PUT 'file:///Users/aaron.white/UMLS/RXNORM/RXNSAT_20251207.RRF' @DAS.DAS_HEALTHCARE_CLAIMS_RAW_DB.DAS_HEALTHCARE_CLAIMS_RAW_DB_INTERNAL_STAGE AUTO_COMPRESS=TRUE;"
snow sql -q "PUT 'file:///Users/aaron.white/UMLS/RXNORM/RXNCUICHANGES_20251207.RRF' @DAS.DAS_HEALTHCARE_CLAIMS_RAW_DB.DAS_HEALTHCARE_CLAIMS_RAW_DB_INTERNAL_STAGE AUTO_COMPRESS=TRUE;"


