CREATE OR REPLACE TABLE DAS.DAS_HEALTHCARE_CLAIMS_RAW_DB.RXNATOMARCHIVE
(
   RXAUI             VARCHAR,
   AUI               VARCHAR,
   STR               VARCHAR,
   ARCHIVE_TIMESTAMP VARCHAR,
   CREATED_TIMESTAMP VARCHAR,
   UPDATED_TIMESTAMP VARCHAR,
   CODE              VARCHAR,
   IS_BRAND          VARCHAR,
   LAT               VARCHAR,
   LAST_RELEASED     VARCHAR,
   SAUI              VARCHAR,
   VSAB              VARCHAR,
   RXCUI             VARCHAR,
   SAB               VARCHAR,
   TTY               VARCHAR,
   MERGED_TO_RXCUI   VARCHAR
);


CREATE OR REPLACE TABLE DAS.DAS_HEALTHCARE_CLAIMS_RAW_DB.RXNCONSO
(
   RXCUI             VARCHAR,
   LAT               VARCHAR,
   TS                VARCHAR,
   LUI               VARCHAR,
   STT               VARCHAR,
   SUI               VARCHAR,
   ISPREF            VARCHAR,
   RXAUI             VARCHAR,
   SAUI              VARCHAR,
   SCUI              VARCHAR,
   SDUI              VARCHAR,
   SAB               VARCHAR,
   TTY               VARCHAR,
   CODE              VARCHAR,
   STR               VARCHAR,
   SRL               VARCHAR,
   SUPPRESS          VARCHAR,
   CVF               VARCHAR
);


CREATE OR REPLACE TABLE DAS.DAS_HEALTHCARE_CLAIMS_RAW_DB.RXNREL
(
   RXCUI1    VARCHAR,
   RXAUI1    VARCHAR,
   STYPE1    VARCHAR,
   REL       VARCHAR,
   RXCUI2    VARCHAR,
   RXAUI2    VARCHAR,
   STYPE2    VARCHAR,
   RELA      VARCHAR,
   RUI       VARCHAR,
   SRUI      VARCHAR,
   SAB       VARCHAR,
   SL        VARCHAR,
   DIR       VARCHAR,
   RG        VARCHAR,
   SUPPRESS  VARCHAR,
   CVF       VARCHAR
);

CREATE OR REPLACE TABLE DAS.DAS_HEALTHCARE_CLAIMS_RAW_DB.RXNSAB
(
   VCUI           VARCHAR,
   RCUI           VARCHAR,
   VSAB           VARCHAR,
   RSAB           VARCHAR,
   SON            VARCHAR,
   SF             VARCHAR,
   SVER           VARCHAR,
   VSTART         VARCHAR,
   VEND           VARCHAR,
   IMETA          VARCHAR,
   RMETA          VARCHAR,
   SLC            VARCHAR,
   SCC            VARCHAR,
   SRL            VARCHAR,
   TFR            VARCHAR,
   CFR            VARCHAR,
   CXTY           VARCHAR,
   TTYL           VARCHAR,
   ATNL           VARCHAR,
   LAT            VARCHAR,
   CENC           VARCHAR,
   CURVER         VARCHAR,
   SABIN          VARCHAR,
   SSN            VARCHAR,
   SCIT           VARCHAR
);


CREATE OR REPLACE TABLE DAS.DAS_HEALTHCARE_CLAIMS_RAW_DB.RXNSAT
(
   RXCUI            VARCHAR,
   LUI              VARCHAR,
   SUI              VARCHAR,
   RXAUI            VARCHAR,
   STYPE            VARCHAR,
   CODE             VARCHAR,
   ATUI             VARCHAR,
   SATUI            VARCHAR,
   ATN              VARCHAR,
   SAB              VARCHAR,
   ATV              VARCHAR,
   SUPPRESS         VARCHAR,
   CVF              VARCHAR
);
 


CREATE OR REPLACE TABLE DAS.DAS_HEALTHCARE_CLAIMS_RAW_DB.RXNSTY
(
   RXCUI          VARCHAR,
   TUI            VARCHAR,
   STN            VARCHAR,
   STY            VARCHAR,
   ATUI           VARCHAR,
   CVF            VARCHAR
);

CREATE OR REPLACE TABLE DAS.DAS_HEALTHCARE_CLAIMS_RAW_DB.RXNDOC
(
    DOCKEY      VARCHAR,
    VALUE       VARCHAR,
    TYPE        VARCHAR,
    EXPL        VARCHAR
);


CREATE OR REPLACE TABLE DAS.DAS_HEALTHCARE_CLAIMS_RAW_DB.RXNCUI
(
 cui1        VARCHAR,
 ver_start   VARCHAR,
 ver_end     VARCHAR,
 cardinality VARCHAR,
 cui2        VARCHAR
);

CREATE OR REPLACE FILE FORMAT DAS.DAS_HEALTHCARE_CLAIMS_RAW_DB.UMLS_RRF_FORMAT
	FIELD_DELIMITER = '|'
	ESCAPE = '\\'
	TRIM_SPACE = TRUE
	NULL_IF = ('', ' ')
	ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
;


COPY INTO DAS.DAS_HEALTHCARE_CLAIMS_RAW_DB.RXNCUI
FROM @DAS.DAS_HEALTHCARE_CLAIMS_RAW_DB.DAS_HEALTHCARE_CLAIMS_RAW_DB_INTERNAL_STAGE/RXNCUI.RRF
FILE_FORMAT = (FORMAT_NAME='DAS.DAS_HEALTHCARE_CLAIMS_RAW_DB.UMLS_RRF_FORMAT');

COPY INTO DAS.DAS_HEALTHCARE_CLAIMS_RAW_DB.RXNDOC
FROM @DAS.DAS_HEALTHCARE_CLAIMS_RAW_DB.DAS_HEALTHCARE_CLAIMS_RAW_DB_INTERNAL_STAGE/RXNDOC.RRF
FILE_FORMAT = (FORMAT_NAME='DAS.DAS_HEALTHCARE_CLAIMS_RAW_DB.UMLS_RRF_FORMAT');

COPY INTO DAS.DAS_HEALTHCARE_CLAIMS_RAW_DB.RXNREL
FROM @DAS.DAS_HEALTHCARE_CLAIMS_RAW_DB.DAS_HEALTHCARE_CLAIMS_RAW_DB_INTERNAL_STAGE/RXNREL.RRF
FILE_FORMAT = (FORMAT_NAME='DAS.DAS_HEALTHCARE_CLAIMS_RAW_DB.UMLS_RRF_FORMAT');

COPY INTO DAS.DAS_HEALTHCARE_CLAIMS_RAW_DB.RXNSAB
FROM @DAS.DAS_HEALTHCARE_CLAIMS_RAW_DB.DAS_HEALTHCARE_CLAIMS_RAW_DB_INTERNAL_STAGE/RXNSAB.RRF
FILE_FORMAT = (FORMAT_NAME='DAS.DAS_HEALTHCARE_CLAIMS_RAW_DB.UMLS_RRF_FORMAT');

COPY INTO DAS.DAS_HEALTHCARE_CLAIMS_RAW_DB.RXNSTY
FROM @DAS.DAS_HEALTHCARE_CLAIMS_RAW_DB.DAS_HEALTHCARE_CLAIMS_RAW_DB_INTERNAL_STAGE/RXNSTY.RRF
FILE_FORMAT = (FORMAT_NAME='DAS.DAS_HEALTHCARE_CLAIMS_RAW_DB.UMLS_RRF_FORMAT');

COPY INTO DAS.DAS_HEALTHCARE_CLAIMS_RAW_DB.RXNCONSO
FROM @DAS.DAS_HEALTHCARE_CLAIMS_RAW_DB.DAS_HEALTHCARE_CLAIMS_RAW_DB_INTERNAL_STAGE/RXNREL.RRF
FILE_FORMAT = (FORMAT_NAME='DAS.DAS_HEALTHCARE_CLAIMS_RAW_DB.UMLS_RRF_FORMAT');

COPY INTO DAS.DAS_HEALTHCARE_CLAIMS_RAW_DB.RXNSAB
FROM @DAS.DAS_HEALTHCARE_CLAIMS_RAW_DB.DAS_HEALTHCARE_CLAIMS_RAW_DB_INTERNAL_STAGE/RXNREL.RRF
FILE_FORMAT = (FORMAT_NAME='DAS.DAS_HEALTHCARE_CLAIMS_RAW_DB.UMLS_RRF_FORMAT');

COPY INTO DAS.DAS_HEALTHCARE_CLAIMS_RAW_DB.RXNSAT
FROM @DAS.DAS_HEALTHCARE_CLAIMS_RAW_DB.DAS_HEALTHCARE_CLAIMS_RAW_DB_INTERNAL_STAGE/RXNREL.RRF
FILE_FORMAT = (FORMAT_NAME='DAS.DAS_HEALTHCARE_CLAIMS_RAW_DB.UMLS_RRF_FORMAT');